SELECT *
FROM   finance_report
WHERE  sourcetradeid IN(SELECT sourcetradeid
                        FROM   finance_report
                        GROUP  BY sourcesystem,
                                  sourcetradeid
                        HAVING Count(*) = 1)
UNION ALL
SELECT fr1.reportdate,
       fr1.sourcesystem,
       fr1.sourcetradeid,
       fr1.assetliabilitycode,
       fr1.gl,
       fr1.gltype,
       fr1.respcentre,
       fr1.bookingtransit,
       fr1.currency,
       fr1.sourceproductcode,
       fr1.productcategorycode,
       fr1.instrumenttype,
       fr1.fsproduct,
       fr1.fsproductgroup,
       fr1.buysellcode,
       fr1.clearancetype,
       fr1.legalentity,
       fr1.lob,
       fr1.counterpartyadaptivecode,
       fr1.counterpartyfullname,
       fr1.intextcode,
       Sum(fr2.cde_npv)            AS CDE_NPV,
       fr1.tc_npv,
       fr1.notional_currency,
       Sum(fr2.tc_notional_value)  AS TC_Notional_Value,
       Sum(fr2.cde_notional_value) AS CDE_Notional_Value,
       fr1.maturitydate,
       fr1.clearinghouseflag,
       fr1.uti,
       fr1.product,
       fr1.swapone_swapid,
       fr1.ws_transaction_id,
       fr1.osfi_instrument_type,
       fr1.product_sub_type_cd,
       fr1.product_group
FROM   finance_report fr1
       JOIN finance_report fr2
         ON fr1.sourcesystem = fr2.sourcesystem
            AND fr1.sourcetradeid = fr2.sourcetradeid
WHERE  fr1.currency = fr1.notional_currency
GROUP  BY fr1.reportdate,
          fr1.sourcesystem,
          fr1.sourcetradeid,
          fr1.assetliabilitycode,
          fr1.gl,
          fr1.gltype,
          fr1.respcentre,
          fr1.bookingtransit,
          fr1.currency,
          fr1.sourceproductcode,
          fr1.productcategorycode,
          fr1.instrumenttype,
          fr1.fsproduct,
          fr1.fsproductgroup,
          fr1.buysellcode,
          fr1.clearancetype,
          fr1.legalentity,
          fr1.lob,
          fr1.counterpartyadaptivecode,
          fr1.counterpartyfullname,
          fr1.intextcode,
          fr1.tc_npv,
          fr1.notional_currency,
          fr1.maturitydate,
          fr1.clearinghouseflag,
          fr1.uti,
          fr1.product,
          fr1.swapone_swapid,
          fr1.tc_notional_value,
          fr1.ws_transaction_id,
          fr1.osfi_instrument_type,
          fr1.product_sub_type_cd,
          fr1.product_group; 