select 
    'BDY' as REC_TYP,
    'IBGC' as SRC_SYS_ID,
    TRADE_ID as DERIV_EXP_TRANS_ID,
    SRC_SYS_CD as TRD_SRC_SYS_ID,
    FACILITY_ID as FAC_ID,
    'DER' as RSK_TYP_CD,
    UEN as BRWR_UEN_ID,
    NVL(RespCentre, RESP_CENTRE) as RESP_NODE,
    NVL(BookingTransit, TRANSIT) as TRANSIT_NO,
    NVL(finance_GL,saccr_GL) as GL_ACCT_NO,
    case when TC_Notional_Value is null then
        case when NOTIONAL is null then ''
             else NOTIONAL_CCY end
    else Notional_Currency end as BAL_AMT_CURR_CD,
    BSL_ASSET_CLASS as BSL_AST_CLS,
    NVL(ClearanceType, OSFI_EXPOSURE_TYPE) as OSFI_EXP_TYP,
    NVL(finance_OSFI_INSTRUMENT_TYPE, saccr_OSFI_INSTRUMENT_TYPE) as OSFI_DERIV_INST_TYP,
    CR_DRV_USED_FOR_CRM_IND as CR_DRV_USED_FOR_CRM_IND,
    COUNTRY_OF_RISK as CNTRY_ULT_RISK_CD,
    PROV_OF_RISK as PROV_ULT_RISK_CD,
    case when CAPITAL_TREATMENT == 'Trading Book' then 'Y' else 'N' end as HLD_TRD_BK_IND,
    FACILITY_PRIMARY_BORROWER_IND as PRIM_BRWR_IND,
    LEGAL_NAME as BRWR_LGL_NM,
    RISK_RTG as BRWR_RISK_RTG,
    SIC_CAD_CD as CDN_SIC_CD,
    SIC_US_CD as US_SIC_CD,
    NAICS_CD as NAIC_CD,
    NIC_CD as NIC_CD,
    NVL(SME_IND, 'N') as SME_IND,
    case when SACCR_NETG_SET_ID like 'N%' then 'Y' else 'N' end as SUB_PER_NET_IND,
    BSL_CREDIT_RISK_APPROACH as CALC_METH_TYP,
    DEFAULT_EXP_IND as DFT_EXP_IND,
    case when MAT_DT is not null
         then case when datediff(MAT_DT,BUS_DATE) < 0 then 0 else datediff(MAT_DT,BUS_DATE) end
         else (case when MAT_IN_DAYS is not null
                then case when MAT_IN_DAYS < 0 then 0 else MAT_IN_DAYS end
                else  0 end
             )
    end as TERM_TO_MAT_DT,
    PD as PD_PCT_PRE_CRM,
    PD as PD_PCT_POST_CRM,
    REPORTING_CCY as EAD_CURR_CD,
    '' as EL_BE_CURR_CD,
    '' as EL_BE_AMT,
    '' as EL_BE_PCT,
    '' as AST_CLS_GUAR_PROV_CRM,
    '' as GUAR_SME_IND,
    '' as DECR_EXP_GUAR_CR_DER_AMT,
    NVL(NVL(TC_Notional_Value, NOTIONAL), SA_NOTIONAL) as BAL_AMT,
    'CAD' as TOT_ANN_SLS_CURR_CD,
    TOT_ANN_SLS_AMT_CAD as TOT_ANN_SLS_AMT,
    case when MTM is not null then MTM_CCY else '' end as REPL_CST_BFR_NET_AMT_CURR_CD,
    MTM as REPL_CST_BFR_NET_AMT,
    case when INT_EXT_CD == 'I' then 'Y' else 'N' end as INTR_BNK_CNTRPRTY_IND,
    'EXP' as BSL_REC_TYP,
    'N'   as VAR_REC_IND,
    'BMO' as LNDR_HOST_CD,
    NVL(PRIMARY_CONNECTION_UEN, UEN) as CMN_RISK_NBR,
    STND_RW as RW_PRE_CRM,
    STND_RW as RW_POST_CRM,
    case when MRGN_IND == 'Y' then 'C' else 'N' end as GUAR_CR_DERIV_OR_COLL_IND,
    RISK_RTG_SYSTEM as BOR_RRS_CD,
    case when QCCP_IND == 'Y' then 'N' else 'Y' end as BLTRL_IND,
    CCP_IND as CCP_IND,
    QCCP_IND as QCCP_IND,
    AVC_IND as AVC_APLBL_IND,
    REPORTING_CCY as CR_VALTN_ADJ_AMT_CURR_CD,
    CVA_LOSS as CR_VALTN_ADJ_AMT,
    case when CCP_IND != 'Y' then ''
         else case when CLEARING_MEMBER_IND == 'Y' then 'CM' else 'CLIENT' end
    end as CR_RSK_BNK_RL_CD,
    CPTY_CD as ACR_CD,
    REPORTING_CCY as VAR_MRGN_AMT_CURR_CD,
    case when ALLOCATED_VM > 0 then ALLOCATED_VM else '' end as VAR_MRGN_RCVD_AMT,
    case when ALLOCATED_VM < 0 then -1 * ALLOCATED_VM else '' end as VAR_MRGN_PSTD_AMT,
    case when MRGN_IND == 'Y' then 'C'  else '' end as STD_COLL_TYP_IND,
    case when QCCP_IND == 'Y' then 'QCCP' else 'BLTRL' end as BCAR_RPTG_CGY,
    RISK_RTG_MODEL as EXP_RRM,
    UNDERLYING_ISSUER as ISSR_CD,
    UNDERLYING_CUSIP as SRC_CUSIP_NBR,
    UNDERLYING_ISIN as SRC_ISIN_NBR,
    QLFY_TXN_CDS_IND as QLFY_TXN_CDS_IND,
    NVL(finance_PRODUCT_SUB_TYPE_CD, saccr_PRODUCT_SUB_TYPE_CODE) as PD_SUB_TP_CD,
    '' as ACCTG_NET_IND,
    case when CLNT_LEG_IND == 'Y' then 'Y'
         else case when CLNT_TRADE_IND == 'Y' then 'N' else '' end
    end as CLI_LEG_IND,
    REPORTING_CCY as INIT_MRGN_CLI_TRD_CURR_CD,
    case when CLNT_LEG_IND == 'Y' then ALLOCATED_NICA else '' end as INIT_MRGN_CLI_TRD_AMT,
    BMO_GUAR_CCP_TO_CLIENT_IND as CLI_TRD_CCP_PERF_GNT_IND,
    CLIENT_LEG_CLEARED_QCCP_IND as CLI_LEG_CLRD_QCCP_IND,
    case when CLNT_LEG_IND == 'Y' then 1 else '' end as CLI_TRD_EAD_SCLR_VAL,
    CCP_LEG_SEG_IND as CLI_TRD_SGRGTD_ACCT_IND,
    PD as BOR_PD_PCT,
    COUNTRY_OF_RESIDENCE as BOR_CNTRY_RES_CD,
    PROV_OF_RESIDENCE as PROV_RES_CD,
    EFF_NOTIONAL as SA_CCR_EFF_NTNL_AMT,
    RC as SA_CCR_REPL_CST_AMT,
    PFE as SA_CCR_POT_EXP_AMT,
    MRGN_IND as MRGN_IND,
    case when QCCP_IND == 'Y' then ''
         when (QCCP_IND != 'Y' and SACVA_IND == 'Y') then 'N'
         when (QCCP_IND != 'Y' and SACVA_IND == 'N') then 'Y'
        else ''
    end as CVA_CPTL_EXMPT_IND,
    SACCR_ASSET_CLASS as SA_CCR_AST_CLS_CGY,
    case when BSL_CREDIT_RISK_APPROACH  == 'AIRB' then AIRB_LGD
         else case when BSL_CREDIT_RISK_APPROACH  == 'FIRB' then FIRB_LGD else '' end
    end as LGD_PCT_PRE_CRM,
    STND_RWA as RWA_STND_AMT,
    RWA as RWA_AMT,
    EFF_MAT as SA_CCR_EFF_MAT,
    CREDIT_DERIVATIVES_SWAP_CLASS as CREDIT_DERIVATIVES_SWAP_CLASS,
    QCCP_RWA_CAP_IND as QCCP_RWA_CAP_IND,
    case when CCP_IND == 'Y' and CLNT_TRADE_IND == 'Y' then 'Y' else '' end as CLI_LEG_LVG_RTO_IND,
    RC_LR as SA_CCR_LVG_RTO_REPL_CST_AMT,
    PFE_LR as SA_CCR_LVG_RTO_POT_EXP_AMT,
    BORROWER_EXT_RTG_SP_EQUIV as BORR_ENTITY_EXT_RTG,
    COUNTRY_EXT_RTG as BORR_CNTRY_EXT_RTG,
    WAIVER_EXEMP_PORTFOLIO_CD as WAIVER_EXEMP_PORTFOLIO_CD,
    '' as CMN_RISK_KMV_NBR,
    '' as CMN_RISK_NM,
    BSL_ASSET_CLASS as BOR_BSL_AST_CLS,
    '' as FAC_PRIM_TYP,
    NVL(BookingTransit, TRANSIT) as FAC_BOOK_TRANSIT_NBR,
    '' as FAC_COMMIT_IND,
    '' as FAC_SHARED_LINK_IND,
    '' as FAC_REVIEW_DT,
    '' as FAC_STATUS_CD,
    '' as FAC_CASH_MSEC_TYP,
    '' as FAC_PRIM_COLL_TYP,
    '' as FAC_SNR_PROF_TYP,
    '' as FAC_SYN_IND,
    '' as FAC_SYN_ROLE_CD,
    RISK_RTG_SYSTEM as FAC_RRS_CD,
    FACILITY_AUTH_AMT as FAC_AUTH_AMT,
    EXPECTED_LOSS as PST_CRM_ELOSS_AMT,
    REG_CAPITAL as REG_CPTL_AMT,
    REG_CAPITAL_DERV as REG_CPTL_AMT_DERV,
    RWA_R_FACTOR as R_FCTR_VAL,
    RWA_K_FACTOR as K_FCTR_VAL,
    RWA_B_FACTOR as B_FCTR_VAL,
    RWA_M_FACTOR as M_FCTR_VAL,
    '' as GUAR_CALC_METH_TYP,
    '' as GUAR_AVC_APLBL_IND,
    '' as GUAR_TOT_ANN_SLS_AMT,
    BORROWER_EXT_RTG as EXT_CRD_RATE,
    case when SUBSTRING(BORROWER_EXT_RTG_NAME, 5, 2) == 'SP' then 'S&P'
         when SUBSTRING(BORROWER_EXT_RTG_NAME, 5, 2) == 'MD' then "MOODY'S"
         when SUBSTRING(BORROWER_EXT_RTG_NAME, 5, 2) == 'FI' then 'FITCH'
         when SUBSTRING(BORROWER_EXT_RTG_NAME, 5, 2) == 'DB' then 'DBRS'
         else 'Unrated'
    end as RATE_AGNC_NAME,
    case when instr(upper(STND_RW_SCENARIO),'SHORT TERM') > 0 then 'Y' else 'N' end as SHRT_TERM_IND,
    '' as GUAR_EXT_CRD_RATE,
    '' as GUAR_RATE_AGNC_NAME,
    '' as GUAR_ENTITY_EXT_RTG,
    RUN_ID as RISKCALC_RUN_ID,
    NVL(finance_PRODUCT_GROUP, saccr_PRODUCT_GROUP) as PRODUCT_GROUP,
    case when (TRADE_ID == SourceTradeId and SRC_SYS_CD == SourceSystem)
         then 'Y' else 'N'
    end as FINANCE_RECON_STATE,
    CONCAT(SRC_SYS_CD ,'-' ,TRADE_ID) as UTI,
    NVL(UTI, CONCAT(SRC_SYS_CD ,'-' ,TRADE_ID)) as RECON_KEY,
    BUS_DATE as BUS_DT,
    MASTER_SCALE as MSE_CODE,
    MAT_DT as MATURITY_DT,
    SACCR_NETG_SET_ID as SACCR_NETTING_SET_ID,
    CLTRL_SET_ID as SACCR_COLLATERAL_SET_ID,
    MTM,
    finance_GL,
    saccr_GL,
    finance_PRODUCT_SUB_TYPE_CD,
    saccr_PRODUCT_SUB_TYPE_CODE
from Joined_Finance_Saccr_Report